### ISSUE TITLE
Add Israeli frequency plan

### ISSUE THREAD

**Issue by t0mZ4** [TheThingsNetwork/lorawan-frequency-plans#33]
#### Summary

Israel has finally approved and legalized the deployment and usage of LoRaWAN networks in Israel.
As a LoRaWAN and TTN/TTI enthusiast and promoter, I would like to contribute and help in defining and adding the regional 
frequency IL917-920 to the ThingsStack

...

#### Why do we need this?

This will allow both community and business users to deploy LoRaWAN in Israel, correctly and legally, publicly and at scale. Until now only pilots were allowed.

...

#### What is already there? What do you see now?

during the pilot, the approved plan was 915-917mhz, and now it was shifted and approved for 917-920.
...

#### What is missing? What do you want to see?

While the Israeli approved plan is similar to AU915 FSB1-2, it is not exactly the same, and therefore a customized plan is required.
...

#### Environment

This will be used only in Israel as far as I know.

This is the official document, there is no English translation yet.

https://www.nevo.co.il/law_word/law06/tak-9301.pdf
Page 12 and Page 13
Section 47

...

#### How do you propose to implement this?

I propose to add IL917-920_FSB_1

...

#### Can you do this yourself and submit a Pull Request?

Yes I have already prepared the yaml file for review.

@htdvisser 

...

**Comment by t0mmyz7** [comment]
I translated the table from the provided PDF, page 13,

![image](https://user-images.githubusercontent.com/31729091/115244293-79db9a00-a12c-11eb-8fb0-1731155caaa9.png)

also I translated some of the relevant requirements from page 12-13, see the attached PDF.

[israeli regulation.pdf](https://github.com/TheThingsNetwork/lorawan-frequency-plans/files/6336403/israeli.regulation.pdf)

**Comment by t0mmyz7** [comment]
quick update, supposedly there will be more info released about the band from lora alliance,  so best to wait for their release as well I suppose

**Comment by htdvisser** [comment]
Thanks for the info!

We indeed can't build this on top of AU915. AU915 is a fixed-channel band, with downlink frequencies fixed on 923.3-927.5 MHz, which can't be used in Israel.

We could perhaps build this on top of the (new) `AS923_FREQ_OFFSET_HZ`, similar tho how the (future) `AS923_3` plan (see #32) with `AS923_FREQ_OFFSET_HZ = -6.60 MHz` has its default channels on 916.6 and 916.8.

But I agree with your last comment that it's probably best to wait for the LoRa Alliance to standardize this before everyone starts investing in something that isn't going anywhere.

**Comment by t0mmyz7** [comment]
You are right on the money, I just learned that the alliance will most likely base this on AS923, and indeed do a frequency shift like in AS923-3

**Comment by t0mmyz7** [comment]
Well now it is official and public knowledge
In RP 1-0-3  : https://lora-alliance.org/resource_hub/rp2-1-0-3-lorawan-regional-parameters/

Israel is set to AS923-4

![image](https://user-images.githubusercontent.com/31729091/120277613-f087bd80-c2bc-11eb-8183-f458cd0a71a1.png)

Defined with the offset feature: AS923_FREQ_OFFSET_HZ= -5.90 MHz

![image](https://user-images.githubusercontent.com/31729091/120277751-2036c580-c2bd-11eb-90db-6b3a87849a51.png)


so we are patiently waiting for #32 

Waiting for an update @htdvisser and to be from the first to test it on TheThingStack :)

**Comment by htdvisser** [comment]
This is currently blocked on The Things Stack support for the RP002 specifications (https://github.com/TheThingsNetwork/lorawan-stack/issues/3513).

While we wait for that I'll update #32 with the preparations for AS923-4.

**Comment by htdvisser** [comment]
With https://github.com/TheThingsNetwork/lorawan-stack/issues/3513 and https://github.com/TheThingsNetwork/lorawan-frequency-plans/pull/32 almost ready, we can unblock this issue and continue working on a TTN-specific plan for Israel.

**Comment by t0mZ4** [comment]
Great news guys, looking forward to test it finally.

**Comment by htdvisser** [comment]
Thanks for your patience, @t0mZ4. It looks like you'll be able to test with the 2-channel plan when The Things Stack v3.18 is released. The next step here is to define the additional 5 or 6 channels that will give us a full frequency plan with 7 or 8 channels.

Channels 1 and 2 are the default channels for all AS923_4 end devices, so it makes sense to have one gateway radio cover channels 1-4. This means that out of the 5 channels we can configure during OTAA Join, we'll always configure 917.7 and 917.9.

That leaves us with 4 more channels that gateway radio 2 can cover, out of which 3 channels that we can configure during OTAA join, and one channel that we can add with a MAC command.

In your table, I see two options for these 3 or 4 additional channels:

1. 3 channels: 5-7
2. 4 channels: 11-14

So the two possible channel plans I see are:

## Option with channel 1-4 and 11-14

| Radio | Freq 0 | Freq 1 | Freq 2 | Freq 3 |
| ----- | ------ | ------ | ------ | ------ |
| Radio 0 | **917.3** | **917.5** | 917.7 | 917.9 |
| Radio 1 | (919.3) | 919.5 | 919.7 | 919.9 |

Here, 919.3 would be the 8th channel. I suspect it may have slightly more interference from the high-power channel at 919.1, so I guess it would be better to prefer the other 3.

## Option with channel 1-7 (+9)

| Radio | Freq 0 | Freq 1 | Freq 2 | Freq 3 |
| ----- | ------ | ------ | ------ | ------ |
| Radio 0 | **917.3** | **917.5** | 917.7 | 917.9 |
| Radio 1 | 918.1 | 918.3 | 918.5* | 918.9* |

Here, 918.5 and 918.9 are directly adjacent to high-power channel 918.7, so these channels could have a bit more interference than the others, so I think the first option would be slightly better.

---

What could also help here is if you (@t0mZ4 or someone else) could get an SDR and do some measurements of the interference on these channels, so that we don't end up in the same situation as with our EU868 channel plan where some users experience interference from passive RFID on 867.5 in urban areas.

cc: @johanstokking

**Comment by htdvisser** [comment]
@t0mZ4 have you been able to take a look at my previous message? Any feedback?

**Comment by htdvisser** [comment]
I'm going to remove this from the Q2 milestone. We need feedback from the local community about the proposal before we can move forward with this.

**Comment by prapuolenis** [comment]
Hi, any plans resuming this topic?

**Comment by KrishnaIyer** [comment]
Thanks for checking in with us. We'll come up with a draft in the next couple of weeks.

**Comment by prapuolenis** [comment]
Hi, also it is important to mention that no dwell time option is a must currently in our network set up.

**Comment by KrishnaIyer** [comment]
Due to scheduling issue, the milestone was moved to `v3.29.0` which is in Jan. I'll get back here early Jan with an update. Sorry for the delay.

**Comment by prapuolenis** [comment]
Hello Krishna,

Thanks for the information, looking forward for the update.

Best Regards

Jonas Prapuolenis   |   Sales engineer
+370 6 8501073
***@***.******@***.***>
***@***.***
Ozo str. 12A-1, LT-08200, Vilnius, Lithuania   |   +370 5 239 4802   |   www.mainlink.net<http://www.mainlink.net/>

**Comment by prapuolenis** [comment]
Hello, what possibilities would be having option 2 frequency range support as an alternative?

**Comment by adriansmares** [comment]
> Hello, what possibilities would be having option 2 frequency range support as an alternative?

Could you please argue why you would prefer option 2 ?

**Comment by prapuolenis** [comment]
Because we have multiple thousands of devices already in field which were configured on AS923-4 1-8 channel range.

**Comment by prapuolenis** [comment]
Hello, any comment?

**Comment by KrishnaIyer** [comment]
We will add support for option 2 for the `v3.29.1` release. @prapuolenis can you please double check the frequencies and make sure that this is what you're looking for?

**Comment by prapuolenis** [comment]
Hello, I am checking with manufacturers RND department, to be completely sure.

**Comment by t0mZ4** [comment]
@prapuolenis since we are both active in lorawan in Israel, let's have a discussion to see how to further improve the ecosystem here? if interested please send me a msg via this [form](https://www.iot-experts.net/lets-talk/)
