### ISSUE TITLE
AS923 Bands can use a better naming convention 

### ISSUE THREAD

**Issue by t0mmyz7** [TheThingsNetwork/lorawan-frequency-plans#35]
Hi

I would like to suggest better naming convention to the AS923 bands.

LoRaWAN Alliance refers to them as AS923-1, AS923-2, AS923-3, AS923-JAPAN and soon AS923-4

Shouldn't the band selection in TTI/TTN be more similar to this notation ? The current one is a bit confusing.

**Comment by nejraselimovic** [comment]
This is because we have to highlight supported channels within a certain frequency band. For example, AS923-1 defines a frequency band [915, 928] MHz, but different countries use different channels inside that band. @johanstokking can you ack? Anything we can do to clarify this, perhaps in the documentation?

**Comment by htdvisser** [comment]
For compatibility reasons we can't change the IDs of existing bands.

The new AS923-1, etc. plans that will be added by https://github.com/TheThingsNetwork/lorawan-frequency-plans/pull/32 will be named `AS_923_1`, etc.
